{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting qiskit\n",
      "  Downloading qiskit-0.36.2.tar.gz (13 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting qiskit-terra==0.20.2\n",
      "  Downloading qiskit_terra-0.20.2-cp38-cp38-win_amd64.whl (6.1 MB)\n",
      "     ---------------------------------------- 6.1/6.1 MB 12.2 MB/s eta 0:00:00\n",
      "Collecting qiskit-aer==0.10.4\n",
      "  Downloading qiskit_aer-0.10.4-cp38-cp38-win_amd64.whl (24.2 MB)\n",
      "     --------------------------------------- 24.2/24.2 MB 19.9 MB/s eta 0:00:00\n",
      "Collecting qiskit-ibmq-provider==0.19.1\n",
      "  Downloading qiskit_ibmq_provider-0.19.1-py3-none-any.whl (240 kB)\n",
      "     ---------------------------------------- 240.0/240.0 KB ? eta 0:00:00\n",
      "Collecting qiskit-ignis==0.7.1\n",
      "  Downloading qiskit_ignis-0.7.1-py3-none-any.whl (198 kB)\n",
      "     ---------------------------------------- 198.7/198.7 KB ? eta 0:00:00\n",
      "Requirement already satisfied: numpy>=1.16.3 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from qiskit-aer==0.10.4->qiskit) (1.21.0)\n",
      "Collecting scipy>=1.0\n",
      "  Downloading scipy-1.8.1-cp38-cp38-win_amd64.whl (36.9 MB)\n",
      "     --------------------------------------- 36.9/36.9 MB 19.8 MB/s eta 0:00:00\n",
      "Requirement already satisfied: requests>=2.19 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from qiskit-ibmq-provider==0.19.1->qiskit) (2.27.1)\n",
      "Requirement already satisfied: websockets>=10.0 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from qiskit-ibmq-provider==0.19.1->qiskit) (10.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.0 in c:\\users\\atish.panda\\appdata\\roaming\\python\\python38\\site-packages (from qiskit-ibmq-provider==0.19.1->qiskit) (2.8.2)\n",
      "Collecting websocket-client>=1.0.1\n",
      "  Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)\n",
      "     ---------------------------------------- 54.3/54.3 KB 2.8 MB/s eta 0:00:00\n",
      "Collecting requests-ntlm>=1.1.0\n",
      "  Using cached requests_ntlm-1.1.0-py2.py3-none-any.whl (5.7 kB)\n",
      "Requirement already satisfied: urllib3>=1.21.1 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from qiskit-ibmq-provider==0.19.1->qiskit) (1.26.9)\n",
      "Requirement already satisfied: setuptools>=40.1.0 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from qiskit-ignis==0.7.1->qiskit) (49.2.1)\n",
      "Collecting retworkx>=0.8.0\n",
      "  Downloading retworkx-0.11.0-cp38-cp38-win_amd64.whl (1.2 MB)\n",
      "     ---------------------------------------- 1.2/1.2 MB 18.5 MB/s eta 0:00:00\n",
      "Collecting stevedore>=3.0.0\n",
      "  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)\n",
      "     ---------------------------------------- 49.7/49.7 KB 2.5 MB/s eta 0:00:00\n",
      "Collecting tweedledum<2.0,>=1.1\n",
      "  Downloading tweedledum-1.1.1-cp38-cp38-win_amd64.whl (1.1 MB)\n",
      "     ---------------------------------------- 1.1/1.1 MB 22.5 MB/s eta 0:00:00\n",
      "Collecting ply>=3.10\n",
      "  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)\n",
      "     ---------------------------------------- 49.6/49.6 KB 2.6 MB/s eta 0:00:00\n",
      "Collecting python-constraint>=1.4\n",
      "  Downloading python-constraint-1.4.0.tar.bz2 (18 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting dill>=0.3\n",
      "  Downloading dill-0.3.5.1-py2.py3-none-any.whl (95 kB)\n",
      "     ---------------------------------------- 95.8/95.8 KB ? eta 0:00:00\n",
      "Collecting sympy>=1.3\n",
      "  Downloading sympy-1.10.1-py3-none-any.whl (6.4 MB)\n",
      "     ---------------------------------------- 6.4/6.4 MB 22.7 MB/s eta 0:00:00\n",
      "Requirement already satisfied: psutil>=5 in c:\\users\\atish.panda\\appdata\\roaming\\python\\python38\\site-packages (from qiskit-terra==0.20.2->qiskit) (5.9.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\atish.panda\\appdata\\roaming\\python\\python38\\site-packages (from python-dateutil>=2.8.0->qiskit-ibmq-provider==0.19.1->qiskit) (1.16.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from requests>=2.19->qiskit-ibmq-provider==0.19.1->qiskit) (2021.10.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from requests>=2.19->qiskit-ibmq-provider==0.19.1->qiskit) (2.0.12)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from requests>=2.19->qiskit-ibmq-provider==0.19.1->qiskit) (2.10)\n",
      "Requirement already satisfied: cryptography>=1.3 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.19.1->qiskit) (36.0.2)\n",
      "Collecting ntlm-auth>=1.0.2\n",
      "  Using cached ntlm_auth-1.5.0-py2.py3-none-any.whl (29 kB)\n",
      "Collecting pbr!=2.1.0,>=2.0.0\n",
      "  Downloading pbr-5.9.0-py2.py3-none-any.whl (112 kB)\n",
      "     -------------------------------------- 112.3/112.3 KB 6.8 MB/s eta 0:00:00\n",
      "Collecting mpmath>=0.19\n",
      "  Downloading mpmath-1.2.1-py3-none-any.whl (532 kB)\n",
      "     ------------------------------------- 532.6/532.6 KB 32.6 MB/s eta 0:00:00\n",
      "Requirement already satisfied: cffi>=1.12 in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.19.1->qiskit) (1.15.0)\n",
      "Requirement already satisfied: pycparser in c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.19.1->qiskit) (2.21)\n",
      "Using legacy 'setup.py install' for qiskit, since package 'wheel' is not installed.\n",
      "Using legacy 'setup.py install' for python-constraint, since package 'wheel' is not installed.\n",
      "Installing collected packages: python-constraint, ply, mpmath, websocket-client, tweedledum, sympy, scipy, retworkx, pbr, ntlm-auth, dill, stevedore, requests-ntlm, qiskit-terra, qiskit-ignis, qiskit-ibmq-provider, qiskit-aer, qiskit\n",
      "  Running setup.py install for python-constraint: started\n",
      "  Running setup.py install for python-constraint: finished with status 'done'\n",
      "  Running setup.py install for qiskit: started\n",
      "  Running setup.py install for qiskit: finished with status 'done'\n",
      "Successfully installed dill-0.3.5.1 mpmath-1.2.1 ntlm-auth-1.5.0 pbr-5.9.0 ply-3.11 python-constraint-1.4.0 qiskit-0.36.2 qiskit-aer-0.10.4 qiskit-ibmq-provider-0.19.1 qiskit-ignis-0.7.1 qiskit-terra-0.20.2 requests-ntlm-1.1.0 retworkx-0.11.0 scipy-1.8.1 stevedore-3.5.0 sympy-1.10.1 tweedledum-1.1.1 websocket-client-1.3.2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\lib\\site-packages)\n",
      "WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.\n",
      "You should consider upgrading via the 'c:\\users\\atish.panda\\appdata\\local\\programs\\python\\python38\\python.exe -m pip install --upgrade pip' command.\n"
     ]
    }
   ],
   "source": [
    "%pip install qiskit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import qiskit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'qiskit-terra': '0.20.2', 'qiskit-aer': '0.10.4', 'qiskit-ignis': '0.7.1', 'qiskit-ibmq-provider': '0.19.1', 'qiskit-aqua': None, 'qiskit': '0.36.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qiskit.__qiskit_version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from qiskit import IBMQ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "configrc.store_credentials:WARNING:2022-06-10 11:48:38,749: Credentials already present. Set overwrite=True to overwrite.\n"
     ]
    }
   ],
   "source": [
    "IBMQ.save_account('698db4ca6d5533a2b2dfe1aeb8da9e7fb1a4c38a9aba47284ab82473b237c6af36b97c4a9210e18c2b9a66af554bd184a8b83032955584fb6f436695c1fe8ae6')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "RequestsApiError",
     "evalue": "\"HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))\"",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mSSLCertVerificationError\u001b[0m                  Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:703\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=701'>702</a>\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=702'>703</a>\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_request(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=703'>704</a>\u001b[0m     conn,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=704'>705</a>\u001b[0m     method,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=705'>706</a>\u001b[0m     url,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=706'>707</a>\u001b[0m     timeout\u001b[39m=\u001b[39;49mtimeout_obj,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=707'>708</a>\u001b[0m     body\u001b[39m=\u001b[39;49mbody,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=708'>709</a>\u001b[0m     headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=709'>710</a>\u001b[0m     chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=710'>711</a>\u001b[0m )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=712'>713</a>\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=713'>714</a>\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=714'>715</a>\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=715'>716</a>\u001b[0m \u001b[39m# mess.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:386\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=384'>385</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=385'>386</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_validate_conn(conn)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=386'>387</a>\u001b[0m \u001b[39mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=387'>388</a>\u001b[0m     \u001b[39m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:1040\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[1;34m(self, conn)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=1038'>1039</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mgetattr\u001b[39m(conn, \u001b[39m\"\u001b[39m\u001b[39msock\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m):  \u001b[39m# AppEngine might not have  `.sock`\u001b[39;00m\n\u001b[1;32m-> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=1039'>1040</a>\u001b[0m     conn\u001b[39m.\u001b[39;49mconnect()\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=1041'>1042</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m conn\u001b[39m.\u001b[39mis_verified:\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connection.py:414\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=411'>412</a>\u001b[0m     context\u001b[39m.\u001b[39mload_default_certs()\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=413'>414</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msock \u001b[39m=\u001b[39m ssl_wrap_socket(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=414'>415</a>\u001b[0m     sock\u001b[39m=\u001b[39;49mconn,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=415'>416</a>\u001b[0m     keyfile\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mkey_file,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=416'>417</a>\u001b[0m     certfile\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcert_file,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=417'>418</a>\u001b[0m     key_password\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mkey_password,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=418'>419</a>\u001b[0m     ca_certs\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mca_certs,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=419'>420</a>\u001b[0m     ca_cert_dir\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mca_cert_dir,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=420'>421</a>\u001b[0m     ca_cert_data\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mca_cert_data,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=421'>422</a>\u001b[0m     server_hostname\u001b[39m=\u001b[39;49mserver_hostname,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=422'>423</a>\u001b[0m     ssl_context\u001b[39m=\u001b[39;49mcontext,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=423'>424</a>\u001b[0m     tls_in_tls\u001b[39m=\u001b[39;49mtls_in_tls,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=424'>425</a>\u001b[0m )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=426'>427</a>\u001b[0m \u001b[39m# If we're using all defaults and the connection\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=427'>428</a>\u001b[0m \u001b[39m# is TLSv1 or TLSv1.1 we throw a DeprecationWarning\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connection.py?line=428'>429</a>\u001b[0m \u001b[39m# for the host.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\util\\ssl_.py:449\u001b[0m, in \u001b[0;36mssl_wrap_socket\u001b[1;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=447'>448</a>\u001b[0m \u001b[39mif\u001b[39;00m send_sni:\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=448'>449</a>\u001b[0m     ssl_sock \u001b[39m=\u001b[39m _ssl_wrap_socket_impl(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=449'>450</a>\u001b[0m         sock, context, tls_in_tls, server_hostname\u001b[39m=\u001b[39;49mserver_hostname\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=450'>451</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=451'>452</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\util\\ssl_.py:493\u001b[0m, in \u001b[0;36m_ssl_wrap_socket_impl\u001b[1;34m(sock, ssl_context, tls_in_tls, server_hostname)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=491'>492</a>\u001b[0m \u001b[39mif\u001b[39;00m server_hostname:\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=492'>493</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m ssl_context\u001b[39m.\u001b[39;49mwrap_socket(sock, server_hostname\u001b[39m=\u001b[39;49mserver_hostname)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/ssl_.py?line=493'>494</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\ssl.py:500\u001b[0m, in \u001b[0;36mSSLContext.wrap_socket\u001b[1;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=493'>494</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mwrap_socket\u001b[39m(\u001b[39mself\u001b[39m, sock, server_side\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=494'>495</a>\u001b[0m                 do_handshake_on_connect\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=495'>496</a>\u001b[0m                 suppress_ragged_eofs\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=496'>497</a>\u001b[0m                 server_hostname\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, session\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=497'>498</a>\u001b[0m     \u001b[39m# SSLSocket class handles server_hostname encoding before it calls\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=498'>499</a>\u001b[0m     \u001b[39m# ctx._wrap_socket()\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=499'>500</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msslsocket_class\u001b[39m.\u001b[39;49m_create(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=500'>501</a>\u001b[0m         sock\u001b[39m=\u001b[39;49msock,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=501'>502</a>\u001b[0m         server_side\u001b[39m=\u001b[39;49mserver_side,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=502'>503</a>\u001b[0m         do_handshake_on_connect\u001b[39m=\u001b[39;49mdo_handshake_on_connect,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=503'>504</a>\u001b[0m         suppress_ragged_eofs\u001b[39m=\u001b[39;49msuppress_ragged_eofs,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=504'>505</a>\u001b[0m         server_hostname\u001b[39m=\u001b[39;49mserver_hostname,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=505'>506</a>\u001b[0m         context\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=506'>507</a>\u001b[0m         session\u001b[39m=\u001b[39;49msession\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=507'>508</a>\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\ssl.py:1040\u001b[0m, in \u001b[0;36mSSLSocket._create\u001b[1;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1038'>1039</a>\u001b[0m             \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mdo_handshake_on_connect should not be specified for non-blocking sockets\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m-> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1039'>1040</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdo_handshake()\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1040'>1041</a>\u001b[0m \u001b[39mexcept\u001b[39;00m (\u001b[39mOSError\u001b[39;00m, \u001b[39mValueError\u001b[39;00m):\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\ssl.py:1309\u001b[0m, in \u001b[0;36mSSLSocket.do_handshake\u001b[1;34m(self, block)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1307'>1308</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msettimeout(\u001b[39mNone\u001b[39;00m)\n\u001b[1;32m-> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1308'>1309</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sslobj\u001b[39m.\u001b[39;49mdo_handshake()\n\u001b[0;32m   <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/ssl.py?line=1309'>1310</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n",
      "\u001b[1;31mSSLCertVerificationError\u001b[0m: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py:440\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=438'>439</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m chunked:\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=439'>440</a>\u001b[0m     resp \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49murlopen(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=440'>441</a>\u001b[0m         method\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mmethod,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=441'>442</a>\u001b[0m         url\u001b[39m=\u001b[39;49murl,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=442'>443</a>\u001b[0m         body\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mbody,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=443'>444</a>\u001b[0m         headers\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mheaders,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=444'>445</a>\u001b[0m         redirect\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=445'>446</a>\u001b[0m         assert_same_host\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=446'>447</a>\u001b[0m         preload_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=447'>448</a>\u001b[0m         decode_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=448'>449</a>\u001b[0m         retries\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=449'>450</a>\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=450'>451</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=452'>453</a>\u001b[0m \u001b[39m# Send the request.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=453'>454</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:813\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=809'>810</a>\u001b[0m     log\u001b[39m.\u001b[39mwarning(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=810'>811</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mRetrying (\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m) after connection broken by \u001b[39m\u001b[39m'\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, retries, err, url\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=811'>812</a>\u001b[0m     )\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=812'>813</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49murlopen(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=813'>814</a>\u001b[0m         method,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=814'>815</a>\u001b[0m         url,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=815'>816</a>\u001b[0m         body,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=816'>817</a>\u001b[0m         headers,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=817'>818</a>\u001b[0m         retries,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=818'>819</a>\u001b[0m         redirect,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=819'>820</a>\u001b[0m         assert_same_host,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=820'>821</a>\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=821'>822</a>\u001b[0m         pool_timeout\u001b[39m=\u001b[39;49mpool_timeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=822'>823</a>\u001b[0m         release_conn\u001b[39m=\u001b[39;49mrelease_conn,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=823'>824</a>\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=824'>825</a>\u001b[0m         body_pos\u001b[39m=\u001b[39;49mbody_pos,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=825'>826</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mresponse_kw\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=826'>827</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=828'>829</a>\u001b[0m \u001b[39m# Handle redirect?\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:813\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=809'>810</a>\u001b[0m     log\u001b[39m.\u001b[39mwarning(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=810'>811</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mRetrying (\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m) after connection broken by \u001b[39m\u001b[39m'\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, retries, err, url\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=811'>812</a>\u001b[0m     )\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=812'>813</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49murlopen(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=813'>814</a>\u001b[0m         method,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=814'>815</a>\u001b[0m         url,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=815'>816</a>\u001b[0m         body,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=816'>817</a>\u001b[0m         headers,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=817'>818</a>\u001b[0m         retries,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=818'>819</a>\u001b[0m         redirect,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=819'>820</a>\u001b[0m         assert_same_host,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=820'>821</a>\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=821'>822</a>\u001b[0m         pool_timeout\u001b[39m=\u001b[39;49mpool_timeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=822'>823</a>\u001b[0m         release_conn\u001b[39m=\u001b[39;49mrelease_conn,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=823'>824</a>\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=824'>825</a>\u001b[0m         body_pos\u001b[39m=\u001b[39;49mbody_pos,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=825'>826</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mresponse_kw\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=826'>827</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=828'>829</a>\u001b[0m \u001b[39m# Handle redirect?\u001b[39;00m\n",
      "    \u001b[1;31m[... skipping similar frames: HTTPConnectionPool.urlopen at line 813 (2 times)]\u001b[0m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:813\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=809'>810</a>\u001b[0m     log\u001b[39m.\u001b[39mwarning(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=810'>811</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mRetrying (\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m) after connection broken by \u001b[39m\u001b[39m'\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, retries, err, url\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=811'>812</a>\u001b[0m     )\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=812'>813</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49murlopen(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=813'>814</a>\u001b[0m         method,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=814'>815</a>\u001b[0m         url,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=815'>816</a>\u001b[0m         body,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=816'>817</a>\u001b[0m         headers,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=817'>818</a>\u001b[0m         retries,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=818'>819</a>\u001b[0m         redirect,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=819'>820</a>\u001b[0m         assert_same_host,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=820'>821</a>\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=821'>822</a>\u001b[0m         pool_timeout\u001b[39m=\u001b[39;49mpool_timeout,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=822'>823</a>\u001b[0m         release_conn\u001b[39m=\u001b[39;49mrelease_conn,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=823'>824</a>\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=824'>825</a>\u001b[0m         body_pos\u001b[39m=\u001b[39;49mbody_pos,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=825'>826</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mresponse_kw\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=826'>827</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=828'>829</a>\u001b[0m \u001b[39m# Handle redirect?\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\connectionpool.py:785\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=782'>783</a>\u001b[0m     e \u001b[39m=\u001b[39m ProtocolError(\u001b[39m\"\u001b[39m\u001b[39mConnection aborted.\u001b[39m\u001b[39m\"\u001b[39m, e)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=784'>785</a>\u001b[0m retries \u001b[39m=\u001b[39m retries\u001b[39m.\u001b[39;49mincrement(\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=785'>786</a>\u001b[0m     method, url, error\u001b[39m=\u001b[39;49me, _pool\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m, _stacktrace\u001b[39m=\u001b[39;49msys\u001b[39m.\u001b[39;49mexc_info()[\u001b[39m2\u001b[39;49m]\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=786'>787</a>\u001b[0m )\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/connectionpool.py?line=787'>788</a>\u001b[0m retries\u001b[39m.\u001b[39msleep()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\api\\session.py:97\u001b[0m, in \u001b[0;36mPostForcelistRetry.increment\u001b[1;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=94'>95</a>\u001b[0m     logger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mRetrying method=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, url=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, status=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, error=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, data=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, headers=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m,\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=95'>96</a>\u001b[0m                  method, url, status, error, data, headers)\n\u001b[1;32m---> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=96'>97</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49mincrement(method\u001b[39m=\u001b[39;49mmethod, url\u001b[39m=\u001b[39;49murl, response\u001b[39m=\u001b[39;49mresponse,\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=97'>98</a>\u001b[0m                          error\u001b[39m=\u001b[39;49merror, _pool\u001b[39m=\u001b[39;49m_pool, _stacktrace\u001b[39m=\u001b[39;49m_stacktrace)\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\urllib3\\util\\retry.py:592\u001b[0m, in \u001b[0;36mRetry.increment\u001b[1;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/retry.py?line=590'>591</a>\u001b[0m \u001b[39mif\u001b[39;00m new_retry\u001b[39m.\u001b[39mis_exhausted():\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/retry.py?line=591'>592</a>\u001b[0m     \u001b[39mraise\u001b[39;00m MaxRetryError(_pool, url, error \u001b[39mor\u001b[39;00m ResponseError(cause))\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/urllib3/util/retry.py?line=593'>594</a>\u001b[0m log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mIncremented Retry for (url=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m): \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, url, new_retry)\n",
      "\u001b[1;31mMaxRetryError\u001b[0m: HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSSLError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\api\\session.py:277\u001b[0m, in \u001b[0;36mRetrySession.request\u001b[1;34m(self, method, url, bare, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=275'>276</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_log_request_info(url, method, kwargs)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=276'>277</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49mrequest(method, final_url, headers\u001b[39m=\u001b[39;49mheaders, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=277'>278</a>\u001b[0m response\u001b[39m.\u001b[39mraise_for_status()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py:529\u001b[0m, in \u001b[0;36mSession.request\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=527'>528</a>\u001b[0m send_kwargs\u001b[39m.\u001b[39mupdate(settings)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=528'>529</a>\u001b[0m resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(prep, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49msend_kwargs)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=530'>531</a>\u001b[0m \u001b[39mreturn\u001b[39;00m resp\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py:645\u001b[0m, in \u001b[0;36mSession.send\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=643'>644</a>\u001b[0m \u001b[39m# Send the request\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=644'>645</a>\u001b[0m r \u001b[39m=\u001b[39m adapter\u001b[39m.\u001b[39;49msend(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=646'>647</a>\u001b[0m \u001b[39m# Total elapsed time of the request (approximately)\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py:517\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=514'>515</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(e\u001b[39m.\u001b[39mreason, _SSLError):\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=515'>516</a>\u001b[0m     \u001b[39m# This branch is for urllib3 v1.22 and later.\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=516'>517</a>\u001b[0m     \u001b[39mraise\u001b[39;00m SSLError(e, request\u001b[39m=\u001b[39mrequest)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/adapters.py?line=518'>519</a>\u001b[0m \u001b[39mraise\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m(e, request\u001b[39m=\u001b[39mrequest)\n",
      "\u001b[1;31mSSLError\u001b[0m: HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mRequestsApiError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Personal Project Work\\Beginner-Python-Projects\\Projects\\Qiskit_test.ipynb Cell 6'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Personal%20Project%20Work/Beginner-Python-Projects/Projects/Qiskit_test.ipynb#ch0000005?line=0'>1</a>\u001b[0m IBMQ\u001b[39m.\u001b[39;49mload_account()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\ibmqfactory.py:177\u001b[0m, in \u001b[0;36mIBMQFactory.load_account\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=173'>174</a>\u001b[0m credentials \u001b[39m=\u001b[39m credentials_list[\u001b[39m0\u001b[39m]\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=174'>175</a>\u001b[0m \u001b[39m# Explicitly check via a server call, to allow environment auth URLs\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=175'>176</a>\u001b[0m \u001b[39m# contain IBM Quantum Experience v2 URL (but not auth) slipping through.\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=176'>177</a>\u001b[0m version_info \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_api_version(credentials)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=178'>179</a>\u001b[0m \u001b[39m# Check the URL is a valid authentication URL.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=179'>180</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m version_info[\u001b[39m'\u001b[39m\u001b[39mnew_api\u001b[39m\u001b[39m'\u001b[39m] \u001b[39mor\u001b[39;00m \u001b[39m'\u001b[39m\u001b[39mapi-auth\u001b[39m\u001b[39m'\u001b[39m \u001b[39mnot\u001b[39;00m \u001b[39min\u001b[39;00m version_info:\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\ibmqfactory.py:444\u001b[0m, in \u001b[0;36mIBMQFactory._check_api_version\u001b[1;34m(credentials)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=436'>437</a>\u001b[0m \u001b[39m\"\"\"Check the version of the remote server in a set of credentials.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=437'>438</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=438'>439</a>\u001b[0m \u001b[39mReturns:\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=439'>440</a>\u001b[0m \u001b[39m    A dictionary with version information.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=440'>441</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=441'>442</a>\u001b[0m version_finder \u001b[39m=\u001b[39m VersionClient(credentials\u001b[39m.\u001b[39mbase_url,\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=442'>443</a>\u001b[0m                                \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcredentials\u001b[39m.\u001b[39mconnection_parameters())\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/ibmqfactory.py?line=443'>444</a>\u001b[0m \u001b[39mreturn\u001b[39;00m version_finder\u001b[39m.\u001b[39;49mversion()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\api\\clients\\version.py:49\u001b[0m, in \u001b[0;36mVersionClient.version\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=35'>36</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mversion\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Dict[\u001b[39mstr\u001b[39m, Union[\u001b[39mbool\u001b[39m, \u001b[39mstr\u001b[39m]]:\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=36'>37</a>\u001b[0m     \u001b[39m\"\"\"Return the version information.\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=37'>38</a>\u001b[0m \n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=38'>39</a>\u001b[0m \u001b[39m    Returns:\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=46'>47</a>\u001b[0m \u001b[39m            * ``api-*`` (str): The versions of each individual API component\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=47'>48</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m---> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/clients/version.py?line=48'>49</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mclient_version_finder\u001b[39m.\u001b[39;49mversion()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\api\\rest\\root.py:102\u001b[0m, in \u001b[0;36mApi.version\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=88'>89</a>\u001b[0m \u001b[39m\"\"\"Return the version information.\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=89'>90</a>\u001b[0m \n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=90'>91</a>\u001b[0m \u001b[39mReturns:\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=98'>99</a>\u001b[0m \u001b[39m        * ``api-*`` (str): The versions of each individual API component\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=99'>100</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=100'>101</a>\u001b[0m url \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mget_url(\u001b[39m'\u001b[39m\u001b[39mversion\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=101'>102</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msession\u001b[39m.\u001b[39;49mget(url)\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=103'>104</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/rest/root.py?line=104'>105</a>\u001b[0m     version_info \u001b[39m=\u001b[39m response\u001b[39m.\u001b[39mjson()\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py:542\u001b[0m, in \u001b[0;36mSession.get\u001b[1;34m(self, url, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=533'>534</a>\u001b[0m \u001b[39mr\u001b[39m\u001b[39m\"\"\"Sends a GET request. Returns :class:`Response` object.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=534'>535</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=535'>536</a>\u001b[0m \u001b[39m:param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=536'>537</a>\u001b[0m \u001b[39m:param \\*\\*kwargs: Optional arguments that ``request`` takes.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=537'>538</a>\u001b[0m \u001b[39m:rtype: requests.Response\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=538'>539</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=540'>541</a>\u001b[0m kwargs\u001b[39m.\u001b[39msetdefault(\u001b[39m'\u001b[39m\u001b[39mallow_redirects\u001b[39m\u001b[39m'\u001b[39m, \u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/requests/sessions.py?line=541'>542</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrequest(\u001b[39m'\u001b[39;49m\u001b[39mGET\u001b[39;49m\u001b[39m'\u001b[39;49m, url, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\atish.panda\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\qiskit\\providers\\ibmq\\api\\session.py:300\u001b[0m, in \u001b[0;36mRetrySession.request\u001b[1;34m(self, method, url, bare, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=296'>297</a>\u001b[0m         \u001b[39m# Modify the original message on the chained exceptions.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=297'>298</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_modify_chained_exception_messages(ex)\n\u001b[1;32m--> <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=299'>300</a>\u001b[0m     \u001b[39mraise\u001b[39;00m RequestsApiError(message, status_code) \u001b[39mfrom\u001b[39;00m \u001b[39mex\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/atish.panda/AppData/Local/Programs/Python/Python38/lib/site-packages/qiskit/providers/ibmq/api/session.py?line=301'>302</a>\u001b[0m \u001b[39mreturn\u001b[39;00m response\n",
      "\u001b[1;31mRequestsApiError\u001b[0m: \"HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))\""
     ]
    }
   ],
   "source": [
    "IBMQ.load_account()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "e5cf268439eddf61ad37bad768a6371fa88c0de579168edb65ec6bbe41af8c40"
  },
  "kernelspec": {
   "display_name": "Python 3.8.8 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
